---
- name: Print Ansible Facts
  hosts: all
  become: false
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts
